stages:
  - build
  - test
  - deploy

building:
  stage: build
  tags:
    - collaudo
  script:
    - make check

# To have the coverage percentage appear as a gitlab badge follow these
# instructions:
# https://docs.gitlab.com/ee/user/project/pipelines/settings.html#test-coverage-parsing
# The coverage parsing string is
# Coverage: \d+\.\d+

testing:
  stage: test
  allow_failure: true
  when: on_success
  tags:
    - collaudo
  only:
    - main
  script:
    - Rscript -e 'devtools::test()'

install:
  stage: deploy
  needs:
    - building
  tags:
    - prod
  allow_failure: false
  when: on_success
  script:
    - make install
  only:
    - tags

install_collaudo:
  stage: deploy
  needs:
    - building
  tags:
    - collaudo
  allow_failure: false
  when: on_success
  script:
    - make install
  only:
    - main

coverage:
  stage: test
  tags:
    - collaudo
  needs:
    - building
  allow_failure: true
  when: on_success
  only:
    - main
  script:
    - make coverage

zero_coverage:
  stage: test
  needs:
    - building
    - coverage
  allow_failure: true
  when: on_success
  only:
    - main
  script:
    - make zero_coverage
