
.default_matrix: &r_matrix
  parallel:
    matrix:
      - R_BIN: "R"
        R_LIBS_USER: "/home/group/public/894cf/.R/4.2.0/library"
        RSCRIPT_BIN: "Rscript"
      - R_BIN: "R-4.4.2"
        R_LIBS_USER: "/home/group/public/894cf/.R/4.4.2/library"
        RSCRIPT_BIN: "Rscript-4.4.2"

stages:
  - build
  - test
  - deploy

building:
  <<: *r_matrix
  stage: build
  #tags:
  #  - collaudo
  script:
    - |
      echo "Using R_BIN=${R_BIN}"
      echo "Using RSCRIPT_BIN=${RSCRIPT_BIN}"
      echo "Using R_LIBS_USER=${R_LIBS_USER}"
    - make check

# To have the coverage percentage appear as a gitlab badge follow these
# instructions:
# https://docs.gitlab.com/ee/user/project/pipelines/settings.html#test-coverage-parsing
# The coverage parsing string is
# Coverage: \d+\.\d+

testing:
  <<: *r_matrix
  stage: test
  allow_failure: true
  when: on_success
  #tags:
  #  - collaudo
  only:
    - main
  script:
    - make test

install:
  <<: *r_matrix
  stage: deploy
  needs:
    - building
  #tags:
  #  - prod
  allow_failure: false
  when: on_success
  script:
    - make install
  only:
    - tags

#install_collaudo:
#  stage: deploy
#  needs:
#    - building
#  tags:
#    - collaudo
#  allow_failure: false
#  when: on_success
#  script:
#    - make install
#  only:
#    - main

coverage:
  <<: *r_matrix
  stage: test
  #tags:
  #  - collaudo
  needs:
    - building
  allow_failure: true
  when: on_success
  only:
    - main
  script:
    - make coverage

zero_coverage:
  <<: *r_matrix
  stage: test
  needs:
    - building
  #  - coverage
  allow_failure: true
  when: on_success
  # only:
  #  - main
  script:
    - make zero_coverage
